### ISSUE TITLE
Bug: Tags not updating

### ISSUE THREAD

**Issue by Joseph-Y** [ijgnd/anki__copy_current_note_contents_to_add_window#1]
Thanks for this great add-on.

I'd like to report a bug in the Anki 2.0 version where tags do not update if the Add Card Window is already prepopulated with tags. They will remain from the previous card unchanged. To be clear, if the previous card had no tags, there is no problem--copied tags will populate. 

I think this has to do with the fact that tags are sticky by default in the Add Card Window. Getting them to "unstick" seems like it would be the root of the solution.

**Comment by ijgnd** [comment]
Thanks for reporting this bug that's also affecting 2.1

There should be multiple ways of fixing it. The easiest one seems to be to clear the tags before I load the new note. This requires one additional line in my code (`addedCardWindow.editor.tags.setText("")`).

Could you change this https://github.com/ijgnd/anki__copy_current_note_contents_to_add_window/blob/master/src/copy_current_note_contents_to_add_window/copycurrent.py#L66 . 

    newnote.tags = note.tags

    addedCardWindow.editor.setNote(newnote)
    addedCardWindow.activateWindow()

into

    newnote.tags = note.tags
    addedCardWindow.editor.tags.setText("")
    addedCardWindow.editor.setNote(newnote)
    addedCardWindow.activateWindow()

Use a text editor like notepad. 

Then restart Anki. 

To find the file copycurrent.py: In you main window click on Tools -> add-ons -> "Open Add-ons Folder". Then you should be in the add-ons folder of your profile. then open the folder "copy_current_note_contents_to_add_window" and you should see the file.  maybe also relevant: https://apps.ankiweb.net/docs/manual.html#file-locations

Does this solve your problem?

**Comment by Joseph-Y** [comment]
Yes, thank you so much. Especially for the quick reply and very clear
explanation.

I came close to this solution yesterday but used ="" instead of the setText
function. I won't forget this now!

**Comment by ijgnd** [comment]
thanks for the confirmation. I just updated the versions on ankiweb.
